# Generated by Django 4.0.3 on 2022-03-09 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_img', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='location not currently available', max_length=25, null=True)),
                ('state', models.CharField(default='State Not Available in Region', max_length=15, null=True)),
                ('county', models.CharField(default='No County Available in Area', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighted', models.DateTimeField()),
                ('bird', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.bird', verbose_name='Bird')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.URLField(max_length=500, null=True)),
                ('age', models.CharField(max_length=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('birds_sighted_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.sighting', verbose_name='Sighting')),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.location', verbose_name='Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='common_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.taxonomy', verbose_name='Common Name'),
        ),
        migrations.AddField(
            model_name='bird',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.location', verbose_name='Region'),
        ),
    ]
