# Generated by Django 4.0.3 on 2022-03-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongSample', models.CharField(default='No Song Currently Available', max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bird',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.song', verbose_name='Song'),
        ),
    ]
