# Generated by Django 4.0.3 on 2022-03-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0002_song_bird_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='county',
            new_name='country',
        ),
    ]
