# Generated by Django 4.0.3 on 2022-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0003_rename_county_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='common_name',
            field=models.CharField(default='Bird', max_length=25, null=True),
        ),
    ]
