# Generated by Django 4.0.3 on 2022-03-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0004_alter_bird_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='song',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
