# Generated by Django 4.0.3 on 2022-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0005_remove_bird_song_delete_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='title',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Class',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='CommonName',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Family',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Genus',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Kingdom',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Order',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Phylum',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='Species',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
