# Generated by Django 4.0.3 on 2022-03-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0006_remove_taxonomy_title_taxonomy_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='common_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.taxonomy', verbose_name='Common Name'),
        ),
    ]
