# Generated by Django 4.0.3 on 2022-03-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0007_alter_bird_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='birds_sighted_id',
        ),
        migrations.AddField(
            model_name='sighting',
            name='watcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.watcher', verbose_name='Watcher'),
        ),
    ]
