# Generated by Django 4.0.3 on 2022-03-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0009_remove_watcher_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watcher',
            old_name='region_id',
            new_name='region',
        ),
    ]
