# Generated by Django 4.0.3 on 2022-03-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0011_remove_sighting_watcher_sighting_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='watcher',
        ),
        migrations.AddField(
            model_name='sighting',
            name='watcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='birdbox.watcher', verbose_name='Watcher'),
        ),
    ]
