# Generated by Django 4.0.3 on 2022-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdbox', '0012_remove_sighting_watcher_sighting_watcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='location',
        ),
        migrations.AddField(
            model_name='bird',
            name='location',
            field=models.ManyToManyField(related_name='location', to='birdbox.location'),
        ),
    ]
